### ISSUE TITLE
Question - obtaining chest inventory

### ISSUE THREAD

**Issue by tastybento** [DeadSilenceIV/AdvancedChestsAPI#2]
Hi,

I am trying to get the advanced chest inventories. I am testing with AdvancedChests 14.2, which might be the issue - maybe I need version 14.3.

I have been using this code, for example:

```
AdvancedChestsAPI.getChestManager().getAdvancedChest(block.getLocation()).getPages().forEach(c -> c.getItems());
```

but I get this error:
```
java.lang.NoSuchMethodError: us.lynuxcraft.deadsilenceiv.advancedchests.chest.AdvancedChest.getPages()Ljava/util/List;
```

Questions:
1. Is this the right way to get the chest items? If not, what do you recommend?
2. If so, do my users need to use version 14.3?
3. Is there a backward compatible way of getting all the items from an advanced chest I can use instead?

**Comment by DeadSilenceIV** [comment]
Hello, i answered you on discord.
