### ISSUE TITLE
Issue: slots cannot be activated / hoppers stuck on chest | Suggestion for further update

### ISSUE THREAD

**Issue by SHIR0SAKI** [DeadSilenceIV/AdvancedChestsAPI#3]
I am using Minecraft Version 1.19.3 Spigot (Git d90018e043c), Java 17, Server hosted by G-Portal

Issue: Item slots cannot be displayed for:
 - sells (default slot 1) for me not so important (I don't use Essensials/other economy mods)
 - search (default slot 3) this is what I want to use!
You may look at the config and chests files (I unfortunately had to transfer into .txt-files) to confirm that everything is alright.
[chests.txt](https://github.com/DeadSilenceIV/AdvancedChestsAPI/files/10368791/chests.txt)
[config.txt](https://github.com/DeadSilenceIV/AdvancedChestsAPI/files/10368792/config.txt)

Screenshot: Activaded "sells", "search", "smelter", "compressor", "page up/down", "sorter"
![2023-01-08_16 16 37](https://user-images.githubusercontent.com/74293889/211207161-83e645b8-ff5d-477a-86b4-4f6d34ae1997.png)

Suggestion:
Also I would like to know if there is a **limit** in the database for the amount of Items/slots. I plan to build a storage with one item there is avaliable in the game, one per chest, an AdvancedChest. A chest named "Storager", I used as a demo for my Server, I already have filled 300 pages, in a few days with my friends, of 2070 and want to expand them to nearly infinite (maybe 102.036.672 slots (1,9 Milion double chests, YES)). Can the database handle that much? Instead of building a huge storage system with too much hoppers that makes the server nearly unplayable I use your Plugin and thank you for that!

Pages:
For this many items it is a pain to cklick through all the pages, one page per click. Instead, would it be possible to implement a function, when holding shift and klick to skip 10 pages at once, or 25, or 50, make this changeble, too? And when holding ctrl and click you can skip 200 or 500 pages and make this also changeable in the chests.yaml? For each chest its own settings?
I would be grateful very much!

We are comming back to the search function I would like to discuss:
At first, it should work on my server and at second, when the chest is sorted, when searching an item, will it jumps to the page where this item is? In the Preview it is nearly the same as I described, but I just want to get sure because I can't check that on the practice.

Last but not least issue: the interaction with **hoppers**:
It appears randomly. Although all relevant chunks are loaded it appears that the items are transfered by the hoppers stuck when they want to get in the AdvancedChest. This issue can be solved temporarely by picking one slot of the items from the stopping hopper and open the chest, putting them inside and closing them. But in most cases helps just replacing the hopper (as a refresh). This can't be a good solution. Reloading the Plugin makes all hopper stop that directed to the chest (replacing hoppers is needed for refresh again). Maybe it is better to cycle the listener and run a updater of the block nearby regulary, I don't know, You know that better, I am not a coder, yet ;)

Thank you for reading, waiting for reply.
Sorry if my suggestions don't belong to the "issues" category, your Discord links are not up to date on SpigotMC-website.

**Comment by DeadSilenceIV** [comment]
Hello, thanks for asking for support.
Please send me a message on my personal discord with your latest.log file. I'd really appreciate if you can send it using 
[https://mclo.gs/](url) **DeadSilenceIV#5307**. I'll be answering all your questions there and i'll update the discord link.
